### ISSUE TITLE
Internal server error response on omnipods, weapons, modules, ammo

### ISSUE THREAD

**Issue by fat4eyes-mwo** [smurfy/mwo-api-sample#12]
Hi, 

I'm getting this response when getting omnipod.json, weapons.json, modules.json and ammo.json:

`{"error":{"code":500,"message":"Internal Server Error"}}`

Did the API change? mechs.json still seems to be good.

**Comment by smurfy** [comment]
nope, but i changed server + some dependencies. i thought i tested the api.  but it seems not all of it.
thanks for the report will fix it soon.

**Comment by smurfy** [comment]
Fixed
